
blank_issues_enabled: false
contact_links:
  - name: Ghid și întrebări frecvente
    url: https://github.com/tbutiu/lejer_eonromania/blob/main/FAQ.md
    about: Documentație și întrebări frecvente” oferă informații detaliate despre utilizarea, configurarea și funcționalitățile integrării, precum și răspunsuri la cele mai comune întrebări ale utilizatorilor.
  - name: Personalizarea cardurilor lovelace
    url: https://github.com/tbutiu/lejer_eonromania/blob/main/SETUP.md
    about: Explică procesul de personalizare și configurare a interfeței utilizatorului în Home Assistant prin crearea și configurarea cardurilor Lovelace pentru afișarea datelor relevante.
