name: "Release"
run-name: "Release ${{ inputs.tag_name || github.ref_name }}"

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release (e.g. v1.0.0)'
        required: true

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    env:
      # This variable unifies the logic: uses input if manual, or ref_name if triggered by tag
      RELEASE_TAG: ${{ inputs.tag_name || github.ref_name }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Verify the release version"
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: true
          PACKAGE_DIR: custom_components/lejer_eonromania
          PACKAGE_NAME: manifest.json
          
      - name: "Compress"
        shell: "bash"
        run: |
          cd custom_components
          zip -r "${{ runner.temp }}/lejer_eonromania.zip" lejer_eonromania

      - name: "Publish"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          draft: true
          files: ${{ runner.temp }}/lejer_eonromania.zip
          body: >
            [![Downloads](https://img.shields.io/github/downloads/tbutiu/lejer_eonromania/${{ env.RELEASE_TAG }}/total?style=flat-square)](https://github.com/tbutiu/lejer_eonromania/releases)
          generate_release_notes: true